#!/bin/bash

# Install coursier
curl -L -o coursier https://git.io/coursier-cli
chmod +x coursier

# Install almond for Scala 2.12
SCALA_VERSION=2.12.8 ALMOND_VERSION=0.3.0
./coursier bootstrap \
  -r jitpack \
  -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
  sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
  --sources --default=true \
  -o almond
./almond --install
rm -f almond

# Install almond for Scala 2.11
SCALA_VERSION=2.11.12 ALMOND_VERSION=0.3.0
./coursier bootstrap \
  -r jitpack \
  -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
  sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
  --sources --default=true \
  -o almond-scala-2.11
./almond-scala-2.11 --install --id scala211 --display-name "Scala (2.11)"
rm -f almond-scala-2.11

# Install required Jupyter/JupyterLab extensions
jupyter labextension install @jupyterlab/plotly-extension
