#!/bin/bash

SCALA_VERSION=2.12.8 ALMOND_VERSION=0.2.1

curl -L -o coursier https://git.io/coursier
chmod +x coursier
./coursier bootstrap \
    -r jitpack \
    -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
    sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
    --sources --default=true \
    -o almond
./almond --install