#!/bin/bash

SCALA_VERSION=2.12.7 ALMOND_VERSION=0.1.12

curl -L -o coursier https://git.io/coursier
chmod +x coursier
./coursier bootstrap \
    -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
    sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
    -o almond
./almond --install